services:

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: statistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d statistics"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 10
