services:

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: ${STATS_POSTGRES_DB:-statistics}
      POSTGRES_USER: ${STATS_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${STATS_POSTGRES_PASSWORD:-postgres}
    ports:
      - "${STATS_POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${STATS_POSTGRES_USER:-postgres} -d ${STATS_POSTGRES_DB:-statistics}"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_DB: ${EWM_POSTGRES_DB:-ewm}
      POSTGRES_USER: ${EWM_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${EWM_POSTGRES_PASSWORD:-postgres}
    ports:
      - "${EWM_POSTGRES_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${EWM_POSTGRES_USER:-postgres} -d ${EWM_POSTGRES_DB:-ewm}"]
      interval: 5s
      timeout: 5s
      retries: 10
