spring:
  application:
    name: stats-server

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:9090"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
