management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

collector:
  kafka:
    bootstrap-server: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: ru.practicum.collector.serializer.CollectorSerializer
    topic-user-actions: stats.user-actions.v1